name: pipeline

on:
  push:
    branches:
      - master
      - dev
      - add-dead-end-filtration
      - test_ci
  pull_request:


jobs:
  test-job:
    runs-on: ubuntu-latest

    defaults:
      run:
        shell: bash -l {0}
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12"]

    env:
      CONDA_FILE: environment.yml

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Setup Conda Environment
        uses: conda-incubator/setup-miniconda@v3
        with:
          miniforge-variant: Mambaforge
          miniforge-version: latest
          use-mamba: true
          activate-environment: cadpythonsim
          channels: conda-forge,

      - name: install conda env
        run: |
          mamba env update -n cadpythonsim -f ${{ env.CONDA_FILE }}

      - name: Install
        run: |
          python -m pip install --upgrade pip
          pip install -e ./[testing]

      - name: Test
        run: |
           pytest
